version: 0.1

log:
  level: info

storage:
  s3:
    region: REGION
    regionendpoint: https://ENDPOINT
    bucket: noco
    accesskey: ACCESS
    secretkey: SECRET
    secure: true
    v4auth: true
    rootdirectory: /registry

proxy:
  remoteurl: https://registry-1.docker.io

http:
  addr: :5000
  secret: mysupersecretstring

  headers:
    X-Content-Type-Options: [nosniff]
