version: '3.9'

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "${REGISTRY_PORT}:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml:ro
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - REGISTRY_HTTP_SECRET=${REGISTRY_HTTP_SECRET}
    restart: unless-stopped
